frontend_url = "https://moneyclaims.perftest.platform.hmcts.net"
respond_to_claim_url = "https://moneyclaims.perftest.platform.hmcts.net/first-contact/start"
idam_api_url = "https://idam-api.perftest.platform.hmcts.net"
dm_url = "http://tmdm-store-perftest.service.perftest.platform.hmcts.net"
doc_assembly_api_url = "http://dg-docassembly-perftest.service.perftest.platform.hmcts.net"
db_host = "preprod-data-lb.moneyclaim.reform.hmcts.net"
capacity = "2"
async_event_operations_enabled = "true"
save_claim_state_enabled = "true"

